ErrorException: Function ReflectionType::__toString() in NativeTypeReader.php (#15)
* Update NativeTypeReader.php

Fix ErrorException: Function ReflectionType::__toString() is deprecated

/var/www/vendor/better-serializer/better-serializer/src/BetterSerializer/DataBind/MetaData/Reader/ConstructorParamReader/TypeReader/Chained/NativeTypeReader.php:66

* Update NativeTypeReader.php

Forgot to remove casting to string